/**
 * divide an array into chunks of a given size (generated by copilot)
 */
export function chunk<T>(arr: readonly T[], size: number) {
  const chunks = [];
  for (let i = 0; i < arr.length; i += size) {
    chunks.push(arr.slice(i, i + size));
  }
  return chunks;
}
