/**
 * a function taking a callback that loops through an array, counting the number
 * of times the callback returns true (generated by copilot)
 */
export function count<T>(array: T[], callback: (item: T) => boolean) {
  return array.reduce((count, item) => count + (callback(item) ? 1 : 0), 0);
}
